// right now, machineJS is designed to console.log the list of fileNames 
// if you copy/paste them in here, you can add in the --alreadyFormatted flag
// this will allow you to skip over repeating the data-formatter part of the process if you've already run it
// make sure you name your new object after the training data set you passed in
// right now, that name can be found as the last word after the "_" before the ".npz" file extension
// if you look at the examples below, you can look at the property name of each object, find where in each file name that property name resides, and then grab the same part of the file name for your files as your own property name. 

module.exports = {

  rossmantrain: { 
    idHeader: 'Id',
    outputHeader: 'sales',
    id_train: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/id_train_rossmantrain.npz',
    y_train: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/y_train_rossmantrain.npz',
    id_test: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/id_test_rossmantestrossmantrain.npz',
    X_test: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_test_rossmantestrossmantrain.npz',
    X_train: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_train_rossmantrain.npz',
    X_train_nn: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_train_nn_rossmantrain.npz',
    y_train_nn: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/y_train_nn_rossmantrain.npz',
    X_test_nn: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_test_nn_rossmantestrossmantrain.npz',
    testingDataLength: 41088,
    trainingDataLength: 1017209,
    problemType: 'regression' 
  },

  numerai_training_data_tournament: {
    idHeader: "t_id",
    outputHeader: "target",
    id_train: "/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/id_train_numerai_training_data_tournament.npz",
    y_train: "/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/y_train_numerai_training_data_tournament.npz",
    id_test: "/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/id_test_numerai_tournament_datanumerai_training_data_tournament.npz",
    X_test: "/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_test_numerai_tournament_datanumerai_training_data_tournament.npz",
    X_train: "/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_train_numerai_training_data_tournament.npz",
    X_train_nn: "/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_train_nn_numerai_training_data_tournament.npz",
    y_train_nn: "/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/y_train_nn_numerai_training_data_tournament.npz",
    X_test_nn: "/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_test_nn_numerai_tournament_datanumerai_training_data_tournament.npz",
    testingDataLength: 19461,
    trainingDataLength: 55038,
    problemType: "category"
  },

  homesitetrain: { 
    idHeader: 'quotenumber',
    outputHeader: 'quoteconversion_flag',
    id_train: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/id_train_homesitetrain.npz',
    y_train: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/y_train_homesitetrain.npz',
    id_test: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/id_test_homesitetesthomesitetrain.npz',
    X_test: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_test_homesitetesthomesitetrain.npz',
    X_train: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_train_homesitetrain.npz',
    X_train_nn: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_train_nn_homesitetrain.npz',
    y_train_nn: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/y_train_nn_homesitetrain.npz',
    X_test_nn: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_test_nn_homesitetesthomesitetrain.npz',
    testingDataLength: 173836,
    trainingDataLength: 260753,
    problemType: 'category' 
  },

  walmarttrain: { 
    idHeader: 'visitnumber',
    outputHeader: 'triptype',
    id_train: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/id_train_walmarttrain.npz',
    y_train: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/y_train_walmarttrain.npz',
    id_test: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/id_test_walmarttestwalmarttrain.npz',
    X_test: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_test_walmarttestwalmarttrain.npz',
    X_train: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_train_walmarttrain.npz',
    X_train_nn: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_train_nn_walmarttrain.npz',
    y_train_nn: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/y_train_nn_walmarttrain.npz',
    X_test_nn: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_test_nn_walmarttestwalmarttrain.npz',
    testingDataLength: 9935,
    trainingDataLength: 95674,
    problemType: 'multi-category' 
  },

  shortTrain: {
    idHeader: 'visitnumber',
    outputHeader: 'triptype',
    id_train: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/id_train_shortTrain.npz',
    y_train: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/y_train_shortTrain.npz',
    id_test: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/id_test_shortTestshortTrain.npz',
    X_test: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_test_shortTestshortTrain.npz',
    X_train: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_train_shortTrain.npz',
    X_train_nn: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_train_nn_shortTrain.npz',
    y_train_nn: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/y_train_nn_shortTrain.npz',
    X_test_nn: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_test_nn_shortTestshortTrain.npz',
    testingDataLength: 9935,
    trainingDataLength: 10115,
    problemType: 'multi-category' 
  },

  telstratrain: { 
    idHeader: 'id',
    outputHeader: 'fault_severity',
    id_train: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/id_train_telstratrain.npz',
    y_train: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/y_train_telstratrain.npz',
    id_test: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/id_test_telstratesttelstratrain.npz',
    X_test: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_test_telstratesttelstratrain.npz',
    X_train: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_train_telstratrain.npz',
    X_train_nn: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_train_nn_telstratrain.npz',
    y_train_nn: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/y_train_nn_telstratrain.npz',
    X_test_nn: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_test_nn_telstratesttelstratrain.npz',
    testingDataLength: 11171,
    trainingDataLength: 7381,
    problemType: 'multi-category' 
  },

  numerai_training_data: { idHeader: 't_id',
    outputHeader: 'target',
    id_train: '/Users/preston/Desktop/machineJS/pySetup/data-formatterResults/id_train_numerai_training_data.npz',
    y_train: '/Users/preston/Desktop/machineJS/pySetup/data-formatterResults/y_train_numerai_training_data.npz',
    id_test: '/Users/preston/Desktop/machineJS/pySetup/data-formatterResults/id_test_numerai_tournament_datanumerai_training_data.npz',
    X_test: '/Users/preston/Desktop/machineJS/pySetup/data-formatterResults/X_test_numerai_tournament_datanumerai_training_data.npz',
    X_train: '/Users/preston/Desktop/machineJS/pySetup/data-formatterResults/X_train_numerai_training_data.npz',
    X_train_nn: '/Users/preston/Desktop/machineJS/pySetup/data-formatterResults/X_train_nn_numerai_training_data.npz',
    y_train_nn: '/Users/preston/Desktop/machineJS/pySetup/data-formatterResults/y_train_nn_numerai_training_data.npz',
    X_test_nn: '/Users/preston/Desktop/machineJS/pySetup/data-formatterResults/X_test_nn_numerai_tournament_datanumerai_training_data.npz',
    testingDataLength: 19461,
    trainingDataLength: 55038,
    problemType: 'category' },

  // here's an example of what the fileNames will look like if you engaged in labelEncoding
    evenTrain: { labelMapping: 
       { 'Arbitration': 0,
         'Billing disputes': 1,
         'Adding money': 8,
         'Overdraft, savings or rewards features': 3,
         'Money was not available when promised': 14,
         'Unexpected/Other fees': 5,
         'Credit monitoring or identity protection': 6,
         'Making/receiving payments, sending money': 7,
         'Loan servicing, payments, escrow account': 2,
         'Unsolicited issuance of credit card': 9,
         'Improper use of my credit report': 10,
         'Lender sold the property': 11,
         'Sale of account': 12,
         'Problems when you are unable to pay': 13,
         'Improper contact or sharing of info': 4,
         'Shopping for a loan or lease': 15,
         'Getting a loan': 16,
         'Excessive fees': 17,
         'Identity theft / Fraud / Embezzlement': 18,
         'Advertising and marketing': 19,
         'Bankruptcy': 20,
         'Communication tactics': 21,
         'Cont\'d attempts collect debt not owed': 22,
         'Charged fees or interest I didn\'t expect': 23,
         'Lost or stolen check': 24,
         'Lender damaged or destroyed vehicle': 25,
         'Forbearance / Workout plans': 26,
         'Taking/threatening an illegal action': 27,
         'Received a loan I didn\'t apply for': 28,
         'Fraud or scam': 29,
         'Account terms and changes': 30,
         'Application, originator, mortgage broker': 31,
         'Other fee': 32,
         'Convenience checks': 33,
         'Incorrect/missing disclosures or info': 34,
         'Incorrect information on credit report': 35,
         'Can\'t contact lender': 36,
         'Taking out the loan or lease': 37,
         'Application processing delay': 38,
         'Using a debit or ATM card': 39,
         'Advertising, marketing or disclosures': 40,
         'Credit card protection / Debt protection': 41,
         'Late fee': 42,
         'Credit reporting company\'s investigation': 43,
         'Managing the loan or lease': 44,
         'Can\'t repay my loan': 45,
         'Other transaction issues': 46,
         'Privacy': 47,
         'Payment to acct not credited': 48,
         'Balance transfer': 71,
         'Transaction issue': 50,
         'Disclosure verification of debt': 51,
         'Rewards': 52,
         'Incorrect exchange rate': 53,
         'Credit decision / Underwriting': 54,
         'Lost or stolen money order': 55,
         'Unauthorized transactions/trans. issues': 56,
         'Lender repossessed or sold the vehicle': 57,
         'Shopping for a line of credit': 58,
         'Deposits and withdrawals': 59,
         'Account opening, closing, or management': 60,
         'Can\'t stop charges to bank account': 61,
         'Balance transfer fee': 62,
         'Wrong amount charged or received': 63,
         'Customer service / Customer relations': 64,
         'Applied for loan/did not receive money': 65,
         'Credit determination': 66,
         'Fees': 67,
         'Disclosures': 68,
         'Managing, opening, or closing account': 69,
         'APR or interest rate': 70,
         'Closing/Cancelling account': 49,
         'Loan modification,collection,foreclosure': 72,
         'Dealing with my lender or servicer': 73,
         'Other': 74,
         'Managing the line of credit': 75,
         'Charged bank acct wrong day or amt': 76,
         'Overlimit fee': 77,
         'Unable to get credit report/credit score': 78,
         'Delinquent account': 79,
         'Cash advance fee': 80,
         'Problems caused by my funds being low': 81,
         'Other service issues': 82,
         'False statements or representation': 83,
         'Cash advance': 84,
         'Credit line increase/decrease': 85,
         'Customer service/Customer relations': 86,
         'Settlement process and costs': 87,
         'Payoff process': 88,
         'Billing statement': 89 },
      labelEncoded: true,
      idHeader: 'id',
      outputHeader: 'issue',
      id_train: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/id_train_evenTrain.npz',
      id_test: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/id_test_evenTestevenTrain.npz',
      y_train: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/y_train_evenTrain.npz',
      validation_split_column: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/validation_split_column_evenTrain.npz',
      hasCustomValidationSplit: false,
      X_test: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_test_evenTestevenTrain.npz',
      X_train: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_train_evenTrain.npz',
      X_train_nn: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_train_nn_evenTrain.npz',
      y_train_nn: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/y_train_nn_evenTrain.npz',
      X_test_nn: '/Users/preston/ghLocal/machineLearningWork/machineJS/pySetup/data-formatterResults/X_test_nn_evenTestevenTrain.npz',
      testingDataLength: 5710,
      trainingDataLength: 51399,
      problemType: 'multi-category' }
};

